name: zipy

services:
  database:
    image: mariadb:11
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app/
      - /app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "4124:4124"
    volumes:
      - ./client:/app/
      - /app/node_modules

volumes:
  db_data: