name: zipy

services:
  database:
    image: postgres:12
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app/
      - /app/node_modules
    depends_on:
      - database

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "4124:4124"
    volumes:
      - ./client:/app/
      - /app/node_modules
    depends_on:
      - server

volumes:
  db_data: